#!/usr/bin/env ruby

desc "lala"
task "top-level" do
  Hobo.ui.info "top level"
end

namespace :test do
  desc "Does non-interactive things"
  task 'non-interactive' do
    Hobo.ui.info Hobo.ui.ask "A question", default: "Used defaults"
  end

  desc 'Performs interactive requests without echo'
  task 'no-echo' do
    Hobo.ui.info Hobo.ui.ask 'A question', echo: false
  end

  task "subcommand" do
    Hobo.ui.info "Subcommand test"
  end

  desc "description"
  long_desc "long description"
  option "-o", "--option", "Option description"
  hidden true
  task "metadata", [ :arg ] do
    Hobo.ui.info "metadata"
  end

  option "--testing=", "description"
  task 'option-test' do |task|
    Hobo.ui.info task.opts[:testing]
  end

  task 'argument-test', [ :test ] do |task, args|
    Hobo.ui.info args[:test]
  end

  task 'unparsed' do |task|
    Hobo.ui.info task.opts[:_unparsed]
  end
end
